/* ─────────────────────────────────────────────────────────────────────────
 * GENERATED FILE — do not hand-edit.
 *
 * Every product name, price and intro paragraph below is copied verbatim from
 * the store's own archived pages:
 *   web.archive.org/web/20250124140153/magillgrainstore.com.au/<slug>/
 *
 * Quirks in the source are preserved deliberately, not cleaned up:
 *   • Horse and Cattle prices read "$000 each" — the store never filled them in.
 *   • Cattle repeats Stock Nuts / Sheep Nuts / Eve & Lamb Nuts.
 *   • Spellings such as "Guniea Pig", "Medow Hay", "Kitter Litter" are theirs.
 * ──────────────────────────────────────────────────────────────────────── */

import type { Product } from "@/lib/site"

export type Category = {
  slug: string
  title: string
  group: string | null
  intro: string[]
  products: Product[]
}

export const catalog: Category[] = [
  {
    slug: "plain-seed-1-10kg",
    title: "Plain Seed 1KG-10KG",
    group: "Grain",
    intro: [],
    products: [],
  },
  {
    slug: "poultry-medicine",
    title: "Poultry Medicine",
    group: "Poultry",
    intro: [],
    products: [],
  },
  {
    slug: "bird-seed-20kg",
    title: "Bird Seed 20KG",
    group: "Birds",
    intro: [
      "Attract a vibrant flock and keep your feeders full with our economical big bags of bird seed mix (20kg)! These larger quantities are perfect for serious bird enthusiasts or those with a high volume of feathered visitors. Offering the same delicious and nutritious blend as our smaller bags, these big bags provide excellent value and ensure a continuous supply of tasty treats for your backyard birds.",
    ],
    products: [
      { name: "Budgie Mix 20KG", price: "$46.50" },
      { name: "Canary Mix 20KG", price: "$46.50" },
      { name: "Finch Mix 20KG", price: "$46.50" },
      { name: "Small Parrot 20KG", price: "$46.50" },
      { name: "Large Parrot 20KG", price: "$32.00" },
      { name: "Special Budgie Mix 20KG", price: "$46.50" },
      { name: "Special Finch Mix 20KG", price: "$46.50" },
      { name: "Black Parrot Adult 15%", price: "$36.50" },
      { name: "Black Parrot B&G 18%", price: "$36.50" },
      { name: "Canary Tonic Mix 20KG", price: "Call For Price" },
      { name: "Fisher Mix 20KG", price: "Call For Price" },
      { name: "Medium Parrot Mix 20KG", price: "Call For Price" },
      { name: "Pigeon Mix 20KG", price: "$25.50" },
      { name: "Pigeon Pellets 20KG", price: "$28.00" },
    ],
  },
  {
    slug: "passwell-wambaroo-and-vitafarm",
    title: "Passwell, Wambaroo And Vitafarm",
    group: "Birds",
    intro: [
      "At Magill Grain Store, we proudly stock products from Passwell, Wambaroo And Vitafarm, three of Australia’s most trusted bird nutrition brands. Whether you’re caring for native wildlife, exotic species, or backyard birds, these brands offer scientifically formulated diets, hand-rearing formulas, and nutritional supplements to support the health and vitality of your feathered friends. Visit us to explore our range and give your birds the best in quality and care.",
    ],
    products: [
      { name: "Complete Lorikeet 500gm", price: "Call For Price" },
      { name: "Hand Rearing Food 500gm", price: "Call For Price" },
      { name: "Crumbles 500gm", price: "Call For Price" },
      { name: "Finch Soft Food 500gm", price: "Call Fort Price" },
      { name: "Parrot Soft Food 500gm", price: "Call For Price" },
      { name: "Budgie Starter 500gm", price: "Call For Price" },
      { name: "Parrot Pellets 500gm", price: "Call For Price" },
      { name: "Red Factor 500gm", price: "Call For Price" },
      { name: "Granivore Rearing Mix 500gm", price: "Call For Price" },
      { name: "Insectivore Mix 250gm", price: "Call For Price" },
      { name: "Complete Lorikeet 1kg", price: "Call For Price" },
      { name: "Hand Rearing Food 1kg", price: "Call For Price" },
      { name: "Crumbles 1kg", price: "Call For Price" },
      { name: "Finch Soft Food 1kg", price: "Call Fort Price" },
      { name: "Egg & Biscuit 1kg", price: "Call For Price" },
      { name: "Parrot Pellets 1kg", price: "Call For Price" },
      { name: "Parrot Soft Food 1kg", price: "Call For Price" },
      { name: "Red Factor 1.5kg", price: "Call For Price" },
      { name: "Granivore Rearing Mix 1kg", price: "Call For Price" },
      { name: "Insectivore Mix 1kg", price: "Call For Price" },
      { name: "Budgie Starter 1kg", price: "Call For Price" },
      { name: "Lorikeet and Honeyeater Food 1.5kg", price: "Call For Price" },
      { name: "Complete Lorikeet 5kg", price: "Call For Price" },
      { name: "Hand Rearing Food 5kg", price: "Call For Price" },
      { name: "Red Factor 5kg", price: "Call For Price" },
      { name: "Crumbles 5KG", price: "Call For Price" },
      { name: "Parrot Soft Food 5kg", price: "Call For Price" },
      { name: "Finch Soft Food 5kg", price: "Call For Price" },
      { name: "Budgies Starter 5kg", price: "Call For Price" },
      { name: "Granviore Rearing Mix 5kg", price: "Call For Price" },
      { name: "Egg and Biscuit 5KG", price: "Call For Price" },
      { name: "Parrot Pellets 5kg", price: "Call For Price" },
      { name: "Lorikeet and Honeyeater Food 9kg", price: "Call For Price" },
      { name: "Complete Lorikeet 10kg", price: "Call For Price" },
      { name: "Hand Rearing Food 10kg", price: "Call For Price" },
      { name: "Parrot Soft Food 10kg", price: "Call For Price" },
      { name: "Crumbles 10kg", price: "Call For Price" },
      { name: "Complete Lorikeet 20kg", price: "Call For Price" },
      { name: "Red Factor 20kg", price: "Call For Price" },
      { name: "Fruit And Nut 20kg", price: "Call For Price" },
      { name: "Egg And Biscuit 20kg", price: "Call For Price" },
      { name: "Parrot Pellets 20kg", price: "Call For Price" },
      { name: "The Good Oil", price: "Call For Price" },
      { name: "Avi-Calcium 125ml", price: "Call For Price" },
      { name: "Avi-Lyte 125ml", price: "Call For Price" },
      { name: "Avi-Vital 125ml", price: "Call For Price" },
      { name: "Piperazine Solutions 125ml", price: "Call For Price" },
      { name: "Terramycine Pinkeye Powder", price: "Call For Price" },
      { name: "Multi-Vite Dog & Cat", price: "Call For Price" },
      { name: "F10 SC", price: "Call For Price" },
      { name: "Multi-Clens 1L", price: "Call For Price" },
      { name: "Avitrol 125ml", price: "Call For Price" },
      { name: "Epi-Otic 237ml", price: "Call For Price" },
      { name: "Multi-Vite Birds 80gm", price: "Call For Price" },
      { name: "Multi-Vite Birds 400gm", price: "Call For Price" },
      { name: "Multi-Vite Birds 750gm", price: "Call For Price" },
      { name: "Tropican", price: "Call For Price" },
      { name: "Tropo Mix 1kg", price: "Call For Price" },
      { name: "Tropo Mix 15kg", price: "Call For Price" },
      { name: "Multi-Vite Birds 750gm", price: "Call For Price" },
    ],
  },
  {
    slug: "litter",
    title: "Litter",
    group: "Cat & Dog",
    intro: [
      "Keep your feline friend happy and healthy with our wide variety of top-quality cat litters! We offer options for all preferences, including lightweight scooping litters for easy cleanup, sustainable wood pellet litters, and odor-absorbing charcoal pellet natural litters. Plus, we have a variety of other options to suit your cat’s needs and create a clean, comfortable environment they’ll love.",
    ],
    products: [
      { name: "Attapulgite 30l", price: "$28.00 each" },
      { name: "Breeder Choice 30l", price: "$28.00 each" },
      { name: "Katz Korner 10kg", price: "$18.50 each" },
      { name: "Kitter Litter 15kg", price: "$24.00 each" },
      { name: "Maxs Cat Litter 12.5kg", price: "$28.50 each" },
      { name: "Natural Cat Litter 5kg", price: "$9.00 each" },
      { name: "Proteq 15kg", price: "$24.00 each" },
    ],
  },
  {
    slug: "food",
    title: "Food",
    group: "Cat & Dog",
    intro: [
      "Fuel your furry companions’ adventures with our selection of delicious and nutritious cat and dog food! We carry a wide range of options to cater to all dietary needs, ages, and activity levels. From premium kibble rich in essential nutrients to grain-free formulas for sensitive stomachs, find the food that keeps your pet happy, healthy, and full of energy. Explore our brands you trust and discover new favorites that will have your furry friend begging for more!",
    ],
    products: [
      { name: "Cobber Country 20kg", price: "$56.00 each" },
      { name: "Cobber Working 20kg", price: "$56.00 each" },
      { name: "Cobber Senior 20kg", price: "$56.00 each" },
      { name: "Cobber Puppy 20kg", price: "$62.00 each" },
      { name: "Great Barko 22kg", price: "$40.00 each" },
      { name: "Uncle Albert 22kg", price: "$42.00 each" },
      { name: "Dibs 22kg", price: "$45.00 each" },
      { name: "Drover 20kg", price: "$40.00 each" },
      { name: "Stockman Grain Free 20KG", price: "Call For Price" },
      { name: "Stockman Working Dog 20KG", price: "Call For Price" },
      { name: "Pedigree Adult 20KG", price: "Call For Price" },
      { name: "BlackHawk Adult 20KG", price: "Call For Price" },
      { name: "CopRice Family Dog 20kg", price: "Call For Price" },
      { name: "Pedigree Adult 20KG", price: "Call For Price" },
      { name: "Stockman Working Dog 20KG", price: "Call For Price" },
      { name: "Stockman Grain Free 20KG", price: "Call For Price" },
      { name: "SuperCoat All Type 20KG", price: "$65.00 each" },
      { name: "Friskies Meaty Grills 10KG", price: "$48.00 each" },
      { name: "Friskies Seafood 10KG", price: "$48.00 each" },
      { name: "Friskies 7 Flavours 10KG", price: "$48.00 each" },
      { name: "Supercoat Small Breed 2.8kg", price: "Call For Price" },
      { name: "Purina Indoor Advantage 2.8kg", price: "Call For Price" },
      { name: "Purina Indoor Advantage 1.4kg", price: "Call For Price" },
      { name: "Purina Urinary Care 2.8kg", price: "Call For Price" },
      { name: "Purina Urinary Care 1.4kg", price: "Call For Price" },
      { name: "Purina Coat & Hairball 1.4kg", price: "Call For Price" },
      { name: "Purina Sensitive Systems 1.4kg", price: "Call For Price" },
      { name: "Purina Healthy Weight 1.4kg", price: "Call For Price" },
      { name: "Purina Healthy Kitten 1.4kg", price: "Call For Price" },
      { name: "Purina Healthy Adult 1.5kg", price: "Call For Price" },
      { name: "Purina Mature Adult 1.4kg", price: "Call For Price" },
      { name: "Purina Healthy Kitten 70gm", price: "Call For Price" },
      { name: "Cobber All Type 2KG", price: "$8.00 each" },
      { name: "Friskies All Type 2KG", price: "$10.00 each" },
      { name: "Snack Bones 1KG", price: "$9.50 each" },
      { name: "Snack Bones 5KG", price: "$34.00 each" },
      { name: "Snack Bones 10KG", price: "$56.00 each" },
      { name: "Breakfast Biskies 4x2 10kg", price: "Call For Price" },
      { name: "Beef Jerky 200gm", price: "$12.00 each" },
      { name: "Liver Jerky 200gm", price: "$12.00 each" },
      { name: "Paddywack (Beef)", price: "$5.00 each" },
      { name: "Cow Ears", price: "$3.20 each" },
      { name: "Lamb Ears", price: "$1.20 each" },
    ],
  },
  {
    slug: "horse",
    title: "Horse",
    group: "Ruminant",
    intro: [],
    products: [
      { name: "Mare & Foal 20kg", price: "$000 each" },
      { name: "Silver Pony Mix 20kg", price: "$000 each" },
      { name: "Gold NB 20kg", price: "$000 each" },
      { name: "Total 20kg", price: "$000 each" },
      { name: "Elite Breed-18 20kg", price: "$000 each" },
      { name: "Cool Horse & Pony 20kg", price: "$000 each" },
      { name: "Cool+ 20kg", price: "$000 each" },
      { name: "Speedi-Beet 20kg", price: "$000 each" },
    ],
  },
  {
    slug: "cattle",
    title: "Cattle",
    group: "Ruminant",
    intro: [],
    products: [
      { name: "Stock Nuts 20KG", price: "$000 each" },
      { name: "Sheep Nuts 20kg", price: "$000 each" },
      { name: "Eve & Lamb Nuts 20KG", price: "$000 each" },
      { name: "Calf Weaner Pellets 20kg", price: "$000 each" },
      { name: "Stock Nuts 20KG", price: "$000 each" },
      { name: "Sheep Nuts 20kg", price: "$000 each" },
      { name: "Eve & Lamb Nuts 20KG", price: "$000 each" },
      { name: "Lamb Pellets 20kg", price: "$000 each" },
    ],
  },
  {
    slug: "goat",
    title: "Goat",
    group: "Ruminant",
    intro: [],
    products: [],
  },
  {
    slug: "ruminant-medicine",
    title: "Ruminant Medicine",
    group: "Ruminant",
    intro: [],
    products: [],
  },
  {
    slug: "rabbit-supplies",
    title: "Rabbit Supplies",
    group: null,
    intro: [
      "Looking to keep your furry friend’s teeth happy and their tummies full? Explore our selection of high-quality rabbit food formulated for optimal health! We offer a variety of options to cater to different breeds and ages, ensuring your rabbit gets the essential nutrients they need to thrive. From tasty pellets packed with fiber for healthy digestion to delicious hay mixes rich in vitamins and minerals, find the perfect food to keep your bunny bouncing with joy!",
    ],
    products: [
      { name: "Jack Rabbit & Guniea Pig (Micro Pellet) 10KG", price: "$16.00 each" },
      { name: "Jack Rabbit & Pet Mix 10KG", price: "$18.50 each" },
      { name: "Jack Rabbit Pellets 20KG", price: "$30.00 each" },
      { name: "Rabbit Hay (Plastic Bag)", price: "$16.00 each" },
    ],
  },
  {
    slug: "fertilizers-1-10kg",
    title: "Fertilizers 1-10KG",
    group: "Fertilizers",
    intro: [
      "Give your plants the nourishing boost they need with our convenient selection of fertilizers in 1kg to 10kg bags! Perfect for smaller gardens, container plants, or targeted feeding, these manageable sizes offer a variety of formulations to meet your specific needs. Whether you’re seeking a general-purpose fertilizer for balanced growth or a specialized blend for flowering plants or vegetables, find the ideal solution to help your garden flourish.",
    ],
    products: [
      { name: "Almunium Sulphate 1KG", price: "$NA each" },
      { name: "Almunium Sulphate 5KG", price: "$NA each" },
      { name: "Almunium Sulphate 10KG", price: "$NA each" },
      { name: "Blade Runner 1KG", price: "$NA each" },
      { name: "Blade Runner 5KG", price: "$NA each" },
      { name: "Blade Runner 10KG", price: "$NA each" },
      { name: "Blood And Bone 1KG", price: "$NA each" },
      { name: "Blood And Bone 5KG", price: "$NA each" },
      { name: "Blood And Bone 10KG", price: "$NA each" },
      { name: "Complete D 1KG", price: "$NA each" },
      { name: "Complete D 5KG", price: "$NA each" },
      { name: "Complete D 10KG", price: "$NA each" },
      { name: "Complete Mineral Mix 1KG", price: "$NA each" },
      { name: "Complete Mineral Mix 5KG", price: "$NA each" },
      { name: "Complete Mineral Mix 10KG", price: "$NA each" },
      { name: "Copper Sulphate Fine 1KG", price: "$NA each" },
      { name: "Copper Sulphate Fine 5KG", price: "$NA each" },
      { name: "Copper Sulphate Fine 10KG", price: "$NA each" },
      { name: "Copper Sulphate Rock 1KG", price: "$NA each" },
      { name: "Copper Sulphate Rock 5KG", price: "$NA each" },
      { name: "Copper Sulphate Rock 10KG", price: "$NA each" },
      { name: "Dolomite Lime 1KG", price: "$NA each" },
      { name: "Dolomite Lime 5KG", price: "$NA each" },
      { name: "Dolomite Lime 10KG", price: "$NA each" },
      { name: "Dusting Sulphur 1KG", price: "$NA each" },
      { name: "Dusting Sulphur 5KG", price: "$NA each" },
      { name: "Dusting Sulphur 10KG", price: "$NA each" },
      { name: "Garden Lime 1KG", price: "$NA each" },
      { name: "Garden Lime 5KG", price: "$NA each" },
      { name: "Garden Lime 10KG", price: "$NA each" },
      { name: "Giganic 1KG", price: "$NA each" },
      { name: "Giganic 5KG", price: "$NA each" },
      { name: "Giganic 10KG", price: "$NA each" },
      { name: "Gypsum 1KG", price: "$NA each" },
      { name: "Gypsum 5KG", price: "$NA each" },
      { name: "Gypsum 10KG", price: "$NA each" },
      { name: "Hydrate Lime (White) 1KG", price: "$NA each" },
      { name: "Hydrate Lime (White) 5KG", price: "$NA each" },
      { name: "Hydrate Lime (White) 10KG", price: "$NA each" },
      { name: "Kahnoona 1KG", price: "$NA each" },
      { name: "Kahnoona 5KG", price: "$NA each" },
      { name: "Kahnoona 10KG", price: "$NA each" },
      { name: "Munns Golf Course Green 1KG", price: "$NA each" },
      { name: "Munns Golf Course Green 5KG", price: "$NA each" },
      { name: "Munns Golf Course Green 10KG", price: "$NA each" },
      { name: "Magnesium Sulphate 1KG", price: "$NA each" },
      { name: "Magnesium Sulphate 5KG", price: "$NA each" },
      { name: "Magnesium Sulphate 10KG", price: "$NA each" },
      { name: "Nitraphoska 1KG", price: "$NA each" },
      { name: "Nitraphoska 5KG", price: "$NA each" },
      { name: "Nitraphoska 10KG", price: "$NA each" },
      { name: "Osmocote 8-9 Months 1KG", price: "$NA each" },
      { name: "Osmocote 8-9 Months 5KG", price: "$NA each" },
      { name: "Osmocote 8-9 Months 10KG", price: "$NA each" },
      { name: "Potassium Nitrate 1KG", price: "$NA each" },
      { name: "Potassium Nitrate 5KG", price: "$NA each" },
      { name: "Potassium Nitrat 10KG", price: "$NA each" },
      { name: "Rapid Raiser 1KG", price: "$NA each" },
      { name: "Rapid Raiser 5KG", price: "$NA each" },
      { name: "Rapid Raiser 10KG", price: "$NA each" },
      { name: "Seamungus 1KG", price: "$NA each" },
      { name: "Seamungus 5KG", price: "$NA each" },
      { name: "Seamungus 10KG", price: "$NA each" },
      { name: "Sudden Impact For Lawns 1KG", price: "$NA each" },
      { name: "Sudden Impact For Lawns 5KG", price: "$NA each" },
      { name: "Sudden Impact For Lawns 10KG", price: "$NA each" },
      { name: "Sulphate Of Ammonia (Grain AM) 1KG", price: "$NA each" },
      { name: "Sulphate Of Ammonia (Grain AM) 5KG", price: "$NA each" },
      { name: "Sulphate Of Ammonia (Grain AM) 10KG", price: "$NA each" },
      { name: "Sulphate Of Potash 1KG", price: "$NA each" },
      { name: "Sulphate Of Potash 5KG", price: "$NA each" },
      { name: "Sulphate Of Potash 10KG", price: "$NA each" },
      { name: "Superphosphate 1KG", price: "$NA each" },
      { name: "Superphosphate 5KG", price: "$NA each" },
      { name: "Superphosphate 10KG", price: "$NA each" },
      { name: "Sulphate Of Iron 1KG", price: "$NA each" },
      { name: "Sulphate Of Iron 5KG", price: "$NA each" },
      { name: "Sulphate Of Iron 10KG", price: "$NA each" },
      { name: "Sudden Impact Buckets 1KG", price: "$NA each" },
      { name: "Sudden Impact Buckets 5KG", price: "$NA each" },
      { name: "Sudden Impact Buckets 10KG", price: "$NA each" },
      { name: "Upsurge 1KG", price: "$NA each" },
      { name: "Upsurge 5KG", price: "$NA each" },
      { name: "Upsurge 10KG", price: "$NA each" },
      { name: "Urea 1KG", price: "$NA each" },
      { name: "Urea 5KG", price: "$NA each" },
      { name: "Urea 10KG", price: "$NA each" },
      { name: "Sulamin 1KG", price: "$NA each" },
      { name: "Sulamin 5KG", price: "$NA each" },
      { name: "Sulamin 10KG", price: "$NA each" },
    ],
  },
  {
    slug: "fertilizers-20-25kg",
    title: "Fertilizers 20-25KG",
    group: "Fertilizers",
    intro: [
      "Cultivate a thriving landscape with our economical bulk fertilizers in 20kg to 25kg bags! Ideal for larger gardens, farms, or frequent use, these larger quantities offer significant cost savings and ensure a steady supply of nutrients for your plants. We carry a variety of high-quality formulations to choose from, including all-purpose blends, slow-release fertilizers, and organic options. Find the perfect fertilizer to nourish your soil and promote healthy, vibrant plant growth throughout the season.",
    ],
    products: [
      { name: "Almunium Sulphate 20KG", price: "$NA each" },
      { name: "Blade Runner 20KG", price: "$22.50 each" },
      { name: "Blood And Bone 25KG", price: "$50.00 each" },
      { name: "Complete D 25KG", price: "$52.00 each" },
      { name: "Complete Mineral Mix 25KG", price: "$52.00 each" },
      { name: "Copper Sulphate Fine 20KG", price: "$200.00 each" },
      { name: "Copper Sulphate Rock 20KG", price: "$250.00 each" },
      { name: "Dolomite Lime 20KG", price: "$11.00 each" },
      { name: "Dusting Sulphur 20KG", price: "$NA each" },
      { name: "Garden Lime 20KG", price: "$11.00 each" },
      { name: "Giganic 20KG", price: "$50.00 each" },
      { name: "Gypsum 20KG", price: "$10.00 each" },
      { name: "Hydrate Lime (White) 20KG", price: "$NA each" },
      { name: "Kahnoona 20KG", price: "$68.00 each" },
      { name: "Munns Golf Course Green 20KG", price: "$68.00 each" },
      { name: "Magnesium Sulphate 25KG", price: "$NA each" },
      { name: "Nitraphoska 20KG", price: "$NA each" },
      { name: "Osmocote 8-9 Months 20KG", price: "$NA each" },
      { name: "Potassium Nitrate 20KG", price: "$NA each" },
      { name: "Rapid Raiser 20KG", price: "$24.00 each" },
      { name: "Seamungus 20KG", price: "$29.50 each" },
      { name: "Sudden Impact For Lawns 20KG", price: "$48.00 each" },
      { name: "Sulphate Of Ammonia (Grain AM) 20KG", price: "$35.50 each" },
      { name: "Sulphate Of Potash 20KG", price: "$59.00 each" },
      { name: "Superphosphate 20KG", price: "$59.50 each" },
      { name: "Sulphate Of Iron 20KG", price: "$49.00 each" },
      { name: "Sudden Impact Buckets 20KG", price: "$55.00 each" },
      { name: "Upsurge 20KG", price: "$32.00 each" },
      { name: "Urea 20KG", price: "$NA each" },
      { name: "Sulamin 20KG", price: "$NA each" },
    ],
  },
  {
    slug: "hay-mulch",
    title: "Hay & Mulch",
    group: null,
    intro: [
      "Support your garden and wildlife with our premium Hay and Mulch products. Ideal for bird nests, pet bedding, or enriching your soil, our selection is natural, high-quality, and versatile. Perfect for bird lovers, gardeners, and pet owners, these products help create a thriving, eco-friendly environment. Keep your outdoor spaces and feathered friends happy with our trusted range of hay and mulch.",
    ],
    products: [
      { name: "Lucerne Chaff 25KG", price: "Call For Price" },
      { name: "Lucerne Hay (Regular/Compact)", price: "$28.00" },
      { name: "Oaten Chaff 25KG", price: "Call For Price" },
      { name: "Wheaten Chaff 25KG", price: "Call For Price" },
      { name: "Medow Hay", price: "Call For Price" },
      { name: "Bedding Hay", price: "$12.50" },
      { name: "Oaten Hay", price: "$24.00" },
      { name: "Pea Straw Bale", price: "$11.50" },
      { name: "Oaten or Meadow Hay – Plastic Bag", price: "$16.00" },
      { name: "Pea Straw – Plastic Bag", price: "$13.50" },
      { name: "Wheat/Barley Straw", price: "$12.50" },
      { name: "Wood Shavings", price: "Call For Price" },
      { name: "Bedding Barley/Straw – Plastic Bag", price: "$16.00" },
    ],
  },
  {
    slug: "laucke-flour",
    title: "Laucke Flour",
    group: null,
    intro: [
      "Calling all baking enthusiasts and aspiring chefs! Our flour and bread mix section offers everything you need to create delicious homemade breads with ease. From classic all-purpose flours perfect for your favorite recipes to convenient bread mixes that simplify the process, we have something for every skill level. Explore our selection of high-quality flours, bread mixes for artisan loaves, focaccia, baguettes, and more! Discover the joy of baking fresh bread at home and fill your kitchen with the irresistible aroma of freshly baked goodness.",
    ],
    products: [
      { name: "Super Soft 10KG", price: "$33.50 each" },
      { name: "Crusty White 10KG", price: "$34.00 each" },
      { name: "Fiber White 10KG", price: "$36.00 each" },
      { name: "Wholemeal 10KG", price: "$34.00 each" },
      { name: "Multi Grain 10KG", price: "$36.00 each" },
      { name: "German Grain 10KG", price: "$36.00 each" },
      { name: "Rye Pre-Mix 10KG", price: "$34.00 each" },
      { name: "Wallaby Bakers 12.5KG", price: "$27.20 each" },
      { name: "Wholemeal Flour 12.5KG", price: "$34.60 each" },
      { name: "Rye Wholemeal 12.5KG", price: "$35.90 each" },
      { name: "Rye Flour T180 12.5KG", price: "$35.90 each" },
      { name: "Spelt Flour 12.5KG", price: "$57.50 each" },
      { name: "Plain Flour 12.5KG", price: "$32.00 each" },
      { name: "Dark Rye Mix 12.5KG", price: "$43.45 each" },
      { name: "Soya Grits Coarse 25KG", price: "$97.15 each" },
    ],
  },
  {
    slug: "pig",
    title: "Pig",
    group: "Others",
    intro: [],
    products: [],
  },
  {
    slug: "rat-mouse",
    title: "Rat & Mouse",
    group: "Others",
    intro: [],
    products: [],
  },
  {
    slug: "kangaroo",
    title: "Kangaroo",
    group: "Others",
    intro: [],
    products: [],
  },
]

export const categoryBySlug = new Map(catalog.map((c) => [c.slug, c]))
